<?php

namespace Database\Seeders;

use App\Models\Dinas;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DinasSeeder extends Seeder
{
    public const DATA = [
        ['Perumdam Tirta Projotamansari Kabupaten Bantul', 'PTPKB', '13100'],
        ['Dinas Kesehatan', 'DK', '10200'],
        ['Dinas Pekerjaan Umum, Perumahan dan Kawasan Permukiman', 'DPUPDKP', '10300'],
        ['Dinas Pertanahan dan Tata Ruang (Kundha Niti Mandala Sarta Tata Sasana)', 'DPDTRKNMST', '10400'],
        ['Badan Perencanaan Pembangunan Daerah', 'BPPD', '10500'],
        ['Dinas Perhubungan', 'DP', '10700'],
        ['Dinas Lingkungan Hidup', 'DLH', '10800'],
        ['Dinas Kependudukan dan Pencatatan Sipil', 'DKDPS', '10900'],
        ['Dinas Sosial', 'DS', '11000'],
        ['Dinas Tenaga Kerja dan Transmigrasi', 'DTKDT', '11100'],
        ['Dinas Koperasi, Usaha Kecil dan Menengah, Perindustrian dan Perdagangan', 'DKUKDMPDP', '11200'],
        ['Satuan Polisi Pamong Praja', 'SPPP', '11300'],
        ['Badan Kesatuan Bangsa dan Politik', 'BKBDP', '11400'],
        ['Sekretariat Dewan Perwakilan Rakyat Daerah', 'SDPRD', '11500'],
        ['Bagian Tata Pemerintahan', 'BTP', '11701'],
        ['Bagian Kesejahteraan Rakyat', 'BKR', '11702'],
        ['Bagian Hukum', 'BH', '11703'],
        ['Bagian Perekonomian Pembangunan dan Sumber Daya Alam', 'BPPDSDA', '11704'],
        ['Bagian Pengadaan Barang dan Jasa', 'BPBDJ', '11705'],
        ['Bagian Umum dan Protokol', 'BUDP', '11706'],
        ['Bagian Organisasi', 'BO', '11707'],
        ['Bagian Perencanaan dan Keuangan', 'BPDK', '11708'],
        ['Dinas Kelautan dan Perikanan', 'DKDP', '11800'],
        ['Badan Pengelolaan Keuangan, Pendapatan dan Aset Daerah', 'BPKPDAD', '11900'],
        ['Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'DPMDPTSP', '12000'],
        ['Inspektorat Daerah', 'ID', '12100'],
        ['Badan Kepegawaian dan Pengembangan Sumberdaya Manusia', 'BKDPSM', '12200'],
        ['Badan Penanggulangan Bencana Daerah', 'BPBD', '12300'],
        ['Dinas Komunikasi dan Informatika', 'DKDI', '12500'],
        ['Dinas Perpustakaan dan Kearsipan', 'DPDK', '12600'],
        ['Dinas Ketahanan Pangan dan Pertanian', 'DKPDP', '12700'],
        ['Dinas Pariwisata', 'DP', '12800'],
        ['Dinas Kebudayaan (Kundha Kabudayan)', 'DKKK', '12900'],
        ['Dinas Pemberdayaan Masyarakat dan Kalurahan', 'DPMDK', '13000'],
        ['PT BPR Bank Bantul (Perseroda)', 'BBBP', '13200'],
        ['Badan Pusat Statistik Kabupaten Bantul', 'BPSKB', '13400'],
        ['Rumah Sakit Umum Daerah Panembahan Senopati', 'RSUDPS', '13500'],
        ['Kantor Pertanahan Kabupaten Bantul', 'KPKB', '13600'],
        ['Balai Pendidikan Menengah Kabupaten Bantul', 'BPMKB', '13700'],
        ['Kejaksaan Negeri Kabupaten Bantul', 'KNKB', '13800'],
        ['Kementerian Agama Kabupaten Bantul', 'KAKB', '13900'],
        ['Lembaga Layanan Pendidikan Tinggi DIY', 'LLPTD', '14000'],
        ['Pengadilan Negeri Kabupaten Bantul', 'PNKB', '14100'],
        ['Kepolisian Resor Bantul', 'KRB', '14200'],
        ['Rumah Tahanan Kelas IIB Kabupaten Bantul', 'RTKIKB', '14300'],
        ['PT Pos Indonesia Kabupaten Bantul', 'PIKB', '14500'],
        ['Bank Indonesia DIY', 'BID', '14600'],
        ['Otoritas Jasa Keuangan DIY', 'OJKD', '14700'],
        ['PT Pegadaian Kabupaten Bantul', 'PKB', '14800'],
        ['Kantor Pelayanan Pajak Daerah Kabupaten Bantul', 'KPPDKB', '14900'],
        ['Kantor Pelayanan Pajak Pratama Kabupaten Bantul', 'KPPPKB', '15000'],
        ['Palang Merah Indonesia (PMI) Kabupaten Bantul', 'PMIPKB', '15100'],
        ['Badan Penyelenggara Jaminan Sosial Kesehatan Kabupaten Bantul', 'BPJSKKB', '20021'],
        ['Badan Meteorologi Klimatologi dan Geofisika Stasiun Geofisika DIY', 'BMKDGSGD', '20020'],
        ['Komisi Pemilihan Umum Kabupaten Bantul', 'KPUKB', '20242'],
        ['Badan Meteorologi Klimatologi dan Geofisika Stasiun Klimatologi DIY', 'BMKDGSKD', '20243'],
        ['Kapanewon Srandakan', 'KS', '20001'],
        ['Kapanewon Sanden', 'KS', '20002'],
        ['Kapanewon Kretek', 'KK', '20003'],
        ['Kapanewon Pundong', 'KP', '20004'],
        ['Kapanewon Bambanglipuro', 'KB', '20005'],
        ['Kapanewon Pandak', 'KP', '20006'],
        ['Kapanewon Pajangan', 'KP', '20007'],
        ['Kapanewon Bantul', 'KB', '20008'],
        ['Kapanewon Jetis', 'KJ', '20009'],
        ['Kapanewon Imogiri', 'KI', '20010'],
        ['Kapanewon Dlingo', 'KD', '20011'],
        ['Kapanewon Banguntapan', 'KB', '20012'],
        ['Kapanewon Pleret', 'KP', '20013'],
        ['Kapanewon Piyungan', 'KP', '20014'],
        ['Kapanewon Sewon', 'KS', '20015'],
        ['Kapanewon Kasihan', 'KK', '20016'],
        ['Kapanewon Sedayu', 'KS', '20017'],
        ['Badan Narkotika Nasional Kabupaten Bantul', 'BNNKB', '20019'],
        ['Kalurahan Sidomulyo', 'KS', '21015'],
        ['Kalurahan Mulyodadi', 'KM', '21016'],
        ['Kalurahan Sumbermulyo', 'KS', '21017'],
        ['Pengadilan Agama Bantul', 'PAB', '20018'],
        ['Kalurahan Temuwuh', 'KT', '21042'],
        ['Kalurahan Terong', 'KT', '21044'],
        ['Kalurahan Jatimulyo', 'KJ', '21043'],
        ['Kalurahan Gadingsari', 'KG', '21003'],
        ['Kalurahan Gadingharjo', 'KG', '21004'],
        ['Kalurahan Srigading', 'KS', '21005'],
        ['Kalurahan Murtigading', 'KM', '21006'],
        ['Kalurahan Donotirto', 'KD', '21009'],
        ['Kalurahan Tirtosari', 'KT', '21010'],
        ['Kalurahan Tirtohargo', 'KT', '21007'],
        ['Kalurahan Tirtomulyo', 'KT', '21011'],
        ['Kalurahan Parangtritis', 'KP', '21008'],
        ['Kalurahan Seloharjo', 'KS', '21012'],
        ['Kalurahan Panjangrejo', 'KP', '21013'],
        ['Kalurahan Srihardono', 'KS', '21014'],
        ['Kalurahan Caturharjo', 'KC', '21018'],
        ['Kalurahan Canden', 'KC', '21028'],
        ['Badan Penyelenggara Jaminan Sosial Ketenagakerjaan Kabupaten Bantul', 'BPJSKKB', '20241'],
        ['Kalurahan Triwidadi', 'KT', '21069'],
        ['Kalurahan Sendangsari', 'KS', '21070'],
        ['Kalurahan Guwosari', 'KG', '21071'],
        ['Kalurahan Argodadi', 'KA', '21072'],
        ['Kalurahan Argorejo', 'KA', '21073'],
        ['Kalurahan Argosari', 'KA', '21074'],
        ['Kalurahan Argomulyo', 'KA', '21075'],
        ['Kalurahan Triharjo', 'KT', '21019'],
        ['Kalurahan Gilangharjo', 'KG', '21020'],
        ['Kalurahan Wijirejo', 'KW', '21021'],
        ['Kalurahan Palbapang', 'KP', '21022'],
        ['Kalurahan Trirenggo', 'KT', '21025'],
        ['Kalurahan Sabdodadi', 'KS', '21026'],
        ['Kalurahan Ringinharjo', 'KR', '21023'],
        ['Kalurahan Wonokromo', 'KW', '21045'],
        ['Kalurahan Pendowoharjo', 'KP', '21061'],
        ['Kalurahan Timbulharjo', 'KT', '21062'],
        ['Kalurahan Bangunharjo', 'KB', '21063'],
        ['Kalurahan Baturetno', 'KB', '21059'],
        ['Dinas Pendidikan, Kepemudaan dan Olahraga', 'DPKDO', '10100'],
        ['Dinas Pemberdayaan Perempuan dan Perlindungan Anak, Pengendalian Penduduk dan Keluarga Berencana', 'DPPDPAPPDK', '12400'],
        ['Badan Amil Zakat Kabupaten Bantul', 'BAZKB', '15200'],
        ['Badan Kependudukan dan Keluarga Berencana Nasional DIY', 'BKDKBND', '20022'],
        ['Kalurahan Bantul', 'KB', '21024'],
        ['Kalurahan Sumberagung', 'KS', '21029'],
        ['Kalurahan Trimulyo', 'KT', '21030'],
        ['Kalurahan Patalan', 'KP', '21027'],
        ['Kalurahan Selopamioro', 'KS', '21031'],
        ['Kalurahan Wukirsari', 'KW', '21038'],
        ['Kalurahan Sriharjo', 'KS', '21032'],
        ['Kalurahan Kebonagung', 'KK', '21033'],
        ['Kalurahan Karangtengah', 'KK', '21034'],
        ['Kalurahan Girirejo', 'KG', '21035'],
        ['Kalurahan Karangtalun', 'KK', '21036'],
        ['Kalurahan Imogiri', 'KI', '21037'],
        ['Kalurahan Mangunan', 'KM', '21039'],
        ['Kalurahan Muntuk', 'KM', '21040'],
        ['Kalurahan Dlingo', 'KD', '21041'],
        ['Kalurahan Banguntapan', 'KB', '21060'],
        ['Kalurahan Jagalan', 'KJ', '21054'],
        ['Kalurahan Singosaren', 'KS', '21055'],
        ['Kalurahan Jambidan', 'KJ', '21057'],
        ['Kalurahan Potorono', 'KP', '21058'],
        ['Kalurahan Tamanan', 'KT', '21053'],
        ['Kalurahan Wirokerten', 'KW', '21056'],
        ['Kalurahan Poncosari', 'KP', '21001'],
        ['Kalurahan Trimurti', 'KT', '21002'],
        ['Kalurahan Pleret', 'KP', '21046'],
        ['Kalurahan Bawuran', 'KB', '21048'],
        ['Kalurahan Wonolelo', 'KW', '21049'],
        ['Kalurahan Sitimulyo', 'KS', '21050'],
        ['Kalurahan Srimulyo', 'KS', '21051'],
        ['Kalurahan Srimartani', 'KS', '21052'],
        ['Kalurahan Bangunjiwo', 'KB', '21065'],
        ['Kalurahan Tirtonirmolo', 'KT', '21066'],
        ['Kalurahan Tamantirto', 'KT', '21067'],
        ['Kalurahan Ngestiharjo', 'KN', '21068'],
        ['Perumda Aneka Dharma Kabupaten Bantul', 'PADKB', '13300'],
        ['PT PLN (Persero) UP3 Yogyakarta', 'PPUY', '14400'],
        ['Kalurahan Segoroyoso', 'KS', '21047'],
        ['Kalurahan Panggungharjo', 'KP', '21064'],
    ];

    public function run(): void
    {
        foreach (self::DATA as $index => $item) {
            // override diskominfo slug manual so admin seeder doesn't break
            $slug = Str::slug($item[1] . '-' . $item[2]);
            if (str_contains(strtolower($item[0]), 'komunikasi dan informatika')) {
                $slug = 'diskominfo';
            }
            
            Dinas::updateOrCreate(
                ['instansi_code' => $item[2]],
                [
                    'nama' => $item[0],
                    'singkatan' => $item[1],
                    'slug' => $slug,
                ]
            );
        }
    }
}